### ISSUE TITLE
Translation of activity.md into Bengali(bn-BD)

### ISSUE THREAD

**Issue by khalid32** [mozilla/mozilla-club-activity-story-of-us#1]
---

title: Story of Us
github: mozilla/mozilla-club-activity-story-of-us
image: phone.png
competencies:
    - {label: "Community Participation", type: "community-participation"}
### সর্বশেষ প্রজেক্ট: আমাদের গল্প

তৈরিকৃত [মজিলা](https://webmaker.org/mentor)ক্লাবের জন্য, প্রজেক্ট-এর ওপরে ভিত্তি করা [WNRC রেডিও রুকিস](https://radiorookies.makes.org/thimble/diy-toolkit-how-to-report-your-own-story). 

শিক্ষার্থীরা নিজেদের গল্প কিভাবে বলবে তা শিখবে, তারা যা শিখেছে তা নিয়ে গভীরভাবে চিন্তা করার জন্য এটি ব্যবহৃত হবে, সামাজিকভাবে শেখার ভূমিকা, এবং কিভাবে তারা ওয়েব এবং তাদের কমিউনিটির সাথে সামনে যেতে শিখতে ও অংশগ্রহণ করতে চায়। এবং ফাইলসমূহ মুক্ত, ওয়েব-বান্ধব উপায়ে বিন্যাশ করে ব্যবহার ও শেয়ার করা যখন যথাযত

১-২ ঘন্টা
### প্রস্তুতি

**কার্যকলাপ আপনি নিজে করুন** এর সাথে পরিচিত হওয়ার জন্য।

প্রিন্ট [গল্প বলা](http://www.scribd.com/doc/198426785/Story-Planning-Worksheet) এবং [রেকর্ডিং টিপস](http://www.scribd.com/doc/198426782/Recording-and-Interviewing-Basics-Worksheet), যদি প্রয়োজন হয়।

**সম্পূর্ণ করুন [প্রাক-কার্যকলাপ প্রশ্নোত্তর](http://goo.gl/forms/kAPPY2NDET)**, এবং আপনার শিক্ষার্থীদেরও সম্পূর্ণ করান [তাদের প্রাক-কার্যকলাপ প্রশ্নাবলী](http://goo.gl/forms/KeeMwn7pMJ)। 

---

১০<br>মিনিট
### আপনার নিজের গল্প বুঝুন

সেশনটি উপস্থাপন করুন এই বলে যে আমরা **সেটা বানাই যা আমরা এই পর্যন্ত শিখেছি** এবং ব্যবহার করুন **ওয়েবের গল্প বলার পদ্ধতিগুলো** যা আমাদের নিজেদের যাত্রা শেয়ার করে এবং আমরা এখান থেকে কোথায় যেতে চাই তা প্রতিফলন করে।

> একটি ভাল "নিজের গল্প"-এ তিনটি অংশ আছে:
> - **আমি।** আপনার গল্পে আপনি কে তা দিয়ে শুরু করুন। এটি আপনার অডিয়েন্সকে আপনার দৃষ্টিভংগী বুঝতে এবং আপনার কন্ঠ ও অভিজ্ঞতার মাঝে আপনার গল্পকে গভীরে নিয়ে যেতে সাহায্য করে। আপনার জীবনের একটি দিক মনোনিবেশ করুন যেখানে আপনি চ্যালেঞ্জের সম্মুখীন হয়েছিলেন এবং বাছাই করেছিলেন। উদাহরণস্বরূপ, কেন আপনি সিদ্ধান্ত নিলেন এই গ্রুপে আসার জন্য?
> - **আমরা।** একটি কার্যকর গল্প আপনার ব্যক্তিগত দৃষ্টিভংগীর সাথে অডিয়েন্সের মধ্যে সেতু তৈরি করে। এই অংশে, আপনার গল্প আপনার অডিয়েন্সের সাথে কেন প্রাসংগিক তা বুঝান।  কি কি চেলেঞ্জ এবং পছন্দ তাদের জন্য অপেক্ষা করছে? উদাহরণস্বরূপ, গ্রুপ হিসেবে, আজকের পর থেকে আপনি কি কি বাধার সম্মুখীন হচ্ছেন, এবং এর জবাব হিসেবে আপনি কি বাছাই করবেন? আপনি কি একসাথে দেখা করা ও শিখানো অব্যাহত রাখবেন? সেটি দেখতে কিরকম হবে?
> - **এখন।** আপনি আপনার অডিয়েন্সকে অনুভব করাতে চান যে তারা পদক্ষেপ নিতে পারে, এবং তারা জানে সেই পদক্ষেপটা কি। এখন এই সুযোগ কি হতে পারে আপনার আইডিয়া দ্বারা উপস্থাপন করুন। উদাহরণস্বরূপ, আপনি কি মনে করেন প্রতি মাসে গ্রুপের মিটিং চালু রাখা উচিৎ? আপনি কি অনলাইনে যোগাযোগ রাখতে চান? পরবর্তিতে কি কি করা যায় তার সুনির্দিষ্ট পথ দিন।

যদি সময় থাকে, এই ছোট্ট, এনিমেটেড ভিডিওটি দেখুন নব্য রিপোর্টার অ্যালেক্স গরডন ভাল ব্যক্তিগত গল্পের উপর প্রাথমিক প্রতিবেদন দেয়া যায় তা ব্যাখ্যা করে।

<iframe src="https://www.youtube.com/embed/BTtbkgO70-E" allowfullscreen="" frameborder="0" height="315" width="420"></iframe>

---

১৫<br>মিনিট
### আপনি আপনার গল্পটি বলুন

**শিক্ষার্থীদের আমন্ত্রণ জানান ছোট গ্রুপে নিজের বর্ণ্না উন্নয়নশীল করানোর জন্য**, তার সাথে নিজের গল্প-এর কাঠামো। প্রত্যেক গ্রুপকে কিছু সময় দিন **প্রথমে নিজে নিজে চিন্তা করতে**, এবং পরে তাদের ছোট গ্রুপে নিজেদের গল্প বলতে বলুন। **প্রতি গল্পকারের জন্য ২-৩ মিনিট করে বরাদ্দ করুন।**

গ্রুপকে জিজ্ঞাসা করুন **একে অপরের কাছে মতামত দিতে**। এই গল্পগুলোর মধ্যে কিরূপ দৃঢ়তা ছিল? এখানে কি কোনো গুরুত্বপূর্ণ তথ্য অথবা প্রসঙ্গ বাদ ছিল? কিভাবে গল্পটি পরবর্তী বলাতে উন্নত হতে পারে?

![কার্যকলাপে পদক্ষেপ](http://mozilla.github.io/webmaker-curriculum/images/story-of-us-03.jpg)

সম্পূর্ণ পড়ুন [Storyboarding and Schematics crash course](https://laura.makes.org/thimble/LTEyNzQ2NzQ2ODg=/schematics-and-storyboards), এবং শিক্ষার্থীরা তাদের গল্পের প্রতিকৃতি করান।

---

২০<br>মিনিট
### রেকর্ড এবং প্রতিফলন: আমাদের গল্প

**এখন রেকর্ড শুরু করুন!** আপনার মোবাইল ফোন অথবা ল্যাপটপের রেকর্ডিং ফাংশন ব্যবহার করে, একে অপরের গল্পগুলো রেকর্ড করে।

<iframe src="http://plotagon.com/player/42510" webkitallowfullscreen="" mozallowfullscreen="" allowfullscreen="" frameborder="0" height="450" width="100%"></iframe>

**আপনার শিক্ষার্থীদের জন্য তাদের গল্প প্রচারে সবচেয়ে যথাযত ওয়েব সার্ভিস কি হতে পারে তা বিবেচনা করুন।** SoundCloud এবং YouTube আপনাকে পোষ্ট করার অনুমতি এবং সহজে আপনার কনটেন্ট লাইসেন্স করে দেয়, এবং Dropbox রেকর্ডিংগুলো জমা ও সংগঠনের জন্য আরেকটি ভাল অপশন। Storify আপনাকে পুরো ওয়েব থেকে কনটেন্ট সংগ্রহ করতে দেয়, শুধু [এই উদাহরন দেখুন](https://storify.com/cpastor24/story-of-us#publiciz)। এনিমেটেড gifs আপনার শিক্ষার্থীরা বানাতে পারে [ওয়েবের বৈচিত্র্যপূর্ণ সেবাসমূহ ব্যবহার করে](https://katermouse.makes.org/thimble/LTIwNjQwNTYzMjA=/creative-commons-gif-exchange-activity)। শিক্ষার্থীদের গল্প ওয়েবে প্রচার করার আরও অনেক পদ্ধতি আছে। আরও উদাহরনের জন্য, [লিস্টটি দেখুন](https://github.com/mozilla/teach.webmaker.org/issues/205#issuecomment-84924930) আসল উদাহরণসমূহ [গ্র্যাগ ম্যাকভেরি](http://twitter.com/jgmac1106)।

[![](https://d262ilb51hltx0.cloudfront.net/max/760/1*4i87-EgCi3HNvV-_--PjTg.gif)](https://medium.com/@leelefever/welcome-to-the-next-golden-age-of-animated-gifs-56c4851ae33e)

আবার অনলাইনে গ্রুপ আলোচনা চালু করা যায়। [আমরা Mozilla Learning forum-এ যুক্ত হওয়ার জন্য সুপারিশ করি, যেখানে তারা একে অপরের সাথে যোগাযোগ রাখতে পারে এবং শিক্ষার্থীদের সাথে দেখা করতে পারে](http://discourse.webmaker.org/category/clubs)।

শিক্ষার্থীরা যেন তাদের রেকর্ডিং আপনার ডিসকাশন ফোরামে প্রচার করে। **ব্যাখ্যা করুন আমাদের পৃথক গল্পগুলো আবার বড় গল্প বলে দেয়:  আমাদের গল্প, আমাদের গ্রুপের গল্প।**

[![সান্ডা হাইটি](http://mozilla.github.io/webmaker-curriculum/images/story-of-us-02.jpg)](http://www.sandahtyte.com/)

**গ্রুপ হিসেবে, আপনার গল্পগুলোর প্রতিফলন করান।** প্রক্রিয়াটি কিরকম ছিল? তারা একে অপরের কাছে কি শিখলো? কিভাবে যোগাযোগ রাখতে চায় এবং একে অপরের সাথে অংশগ্রহণ করতে চায়, মনে রাখতে হবে উভয় সমকালীন ও অসমকালীন আলোচনার অপশনগুলো?

একটি সিদ্ধান্ত দিয়ে সমাপ্ত করুন **এখান থেকে তারা কোথায় যেতে চায়**।

২টি প্রাক-কার্যকলাপ প্রশ্নোত্তরগুলো সম্পূর্ণ করে সমাপ্ত করুন: একটি [আপনার শিক্ষার্থীদের জন্য](http://goo.gl/forms/8UWO57WswT), এবং আরেকটি [আপনার জন্য](http://goo.gl/forms/gUaeABnBuh)।

**Comment by soapdog** [comment]
Heeeey!!!! Thanks a lot for this translation! Its now live at http://mozilla.github.io/mozilla-club-activity-story-of-us/#bn we now have 50% of our activities curriculum already translated into Bengali. Thank you :smile_cat: this is awesome!
