### ISSUE TITLE
Localization of aside.md into Hindi

### ISSUE THREAD

**Issue by join2ashish** [mozilla/mozilla-club-activity-story-of-us#10]
#### दर्शक
-  ८ +
-  प्रणाली विचारकों से शुरुआत
#### सामग्री
-  कलम और कागज
- (इच्छानुसार) मोबाइल फोन, लैपटॉप या अन्य वीडियो / ऑडियो रिकॉर्डिंग उपकरण
- (इच्छानुसार) [मुद्रित कहानी कहने की कला](http://www.scribd.com/doc/198426785/Story-Planning-Worksheet) और  [रिकॉर्डिंग सुझाव](http://www.scribd.com/doc/198426782/Recording-and-Interviewing-Basics-Worksheet).
#### सीखने का  मकसद
-  खुले , वेब के अनुकूल स्वरूपों में फ़ाइलो का उपयोग करें और उससे बाटें भी 
- तुल्यकालिक और अतुल्यकालिक चर्चाओं दोनों में भाग ले
- एक विशेष योगदान के लिए उपयोग करने के लिए एक वेब उपकरण चुनें
### गतिविधि में कार्रवाई करें !

![हमारी कहानी कार्रवाही में !](http://mozilla.github.io/webmaker-curriculum/images/story-of-us-01.jpg)
[डब्लू ऐन वाई सी रेडियो रूकिएस अपनी कहानी बता रहे हैं ](http://hivenyc.org/portfolio/digital-citizenship-kit/).
#### समुदाय रीमिक्स देखें

हमारे [ चर्चा मंच ] में शिक्षकों और कार्यकर्ताओं को उनकी विशिष्ट दर्शकों के लिए इस गतिविधि को संशोधित किया है तरीकों की जाँच करें(http://discourse.webmaker.org/t/testing-3-participating-on-the-web/1211).

**Comment by soapdog** [comment]
Thanks a lot for the continuous and awesome work! Your contribution is live at:

http://mozilla.github.io/mozilla-club-activity-story-of-us/#hi

Please review it if you can since I had to tweak some of the Markdown syntax and HTML links.

:smile_cat:
