### ISSUE TITLE
Localization of activity.md into Hindi

### ISSUE THREAD

**Issue by join2ashish** [mozilla/mozilla-club-activity-story-of-us#12]
---

शीर्षक: हमारी कहानी
गिटहब : मोज़िला/मोज़िला-सभा-गतिविधि--हमारी-कहानी
तस्वीर: फ़ोन.पीएनजी 
दक्षताओं:
    - {लेबल: "समुदाय की भागीदारी", प्रकार: "समुदाय-की-भागीदारी"}
### अंतिम परियोजना: हमारी कहानी

सभा के लिए [मोज़िला] द्वारा बनाया गया (https://webmaker.org/mentor) , [ डब्लू ऐन वाई सी रेडियो रूकीज़ ] परियोजना पर आधारित (https://radiorookies.makes.org/thimble/diy-toolkit-how-to-report-your-own-story). 

शिक्षार्थियों सीखेंगे की उन्हें अपनी कहानी कैसे बतानी चाहिए , वे क्या सीखते है उसे प्रतिबिंबित करने के लिए इसका इस्तेमाल करते हैं, सामाजिक रूप से सीखने, और वे कैसे जानने के लिए और वेब पर और अपने समुदाय को आगे जाने के साथ भाग लेने के लिए की भूमिका हैं और उसका  उपयोग और खुले, वेब के अनुकूल स्वरूपों में फ़ाइलों को साझा करें  जब उसका समय उचित हो। 

१ - २ घंटे 
### तैयारी

गतिविधि को खुद से करें उससे सही रूप से परिचित होने के लिए 

प्रिंट [ कहानी कहने ](http://www.scribd.com/doc/198426785/Story-Planning-Worksheet) और [ रिकॉर्डिंग सुझाव ](http://www.scribd.com/doc/198426782/Recording-and-Interviewing-Basics-Worksheet), यदि ज़रूरत हो तो

*\* [ पूर्व गतिविधि प्रश्नावली ] को पूरा करें(http://goo.gl/forms/kAPPY2NDET)**, और आपके पास शिक्षार्थियों हैं तो  [ उनके पूर्व गतिविधि प्रश्नावली ] पूरा करें (http://goo.gl/forms/KeeMwn7pMJ). 

---

१ ० <बी आर >मिनट 
### स्वयं की अपनी कहानी को समझें

सत्र से परिचय कराईये की हम लोग उसका निर्माण करेंगे जो हमने अभी तक सीखा और वेब कहानी बताने वाली तकनीक का इस्तेमाल करेंगे बाटने के लिए  और प्रतिबिबिद जहाँ से हम लोग यहाँ से जायेंगे .

> एक अछि "स्वयं की कहानी " के ३ भाग है :
> - **मैं  .** आप अपनी कहानी उससे बताये जो आप हैं . यह आपकी आवाज और अनुभव में अपने दृष्टिकोण और मैदान में अपनी कहानी को समझने के लिए अपने दर्शकों में मदद करता है. Focus on an aspect of your life where you faced a challenge and made a choice. For example, why did you decide to come to this group?
> - **हम .** एक प्रभावी कहानी अपने दर्शकों के साथ अपने व्यक्तिगत दृष्टिकोण को पुल की  तरह जोड़ती हैं . इस भाग में, क्यों अपनी कहानी अपने दर्शकों के लिए प्रासंगिक है , समझाएं . क्या चुनौतियों और विकल्प उन्हें इंतजार है ? उदाहरण के लिए, एक समूह के रूप में , क्या बाधाएं आज के बाद आप का सामना करना होगा , और जवाब में क्या विकल्प है तुम्हारे पास? आप को पूरा करने और एक साथ जानने के लिए जारी रहेगा?  ऐसा क्या लग जाएगा?
> - **अब.** आप अपने दर्शक को छोड़ना चाहते है क्यूंकि आप महसूस कर रहे हैं की वो कार्यवाही कर सकते हैं , और उन्हें पता है की क्या कार्यवाही करनी है . अपने विचार प्रस्तुत करें की अभी क्या अवसर है ।  उदाहरण के लिए, यदि आप समूह में हर महीने बैठक जारी रखना चाहिए ऐसा लगता है? आप ऑनलाइन संपर्क में रहना चाहते हैं? तो ऐसे ठोस कदम ले की आगे और क्या कर सकते हैं !

अगर समय अनुमति देता है तो इस छोटी सी एनिमेटेड वीडियो को देखें जिसमे रूकी रिपोर्टर एलेक्सिस गॉरडन अच्छी कहानी रिपोर्ट करने के बेसिक्स बताते हैं 

<iframe src="https://www.youtube.com/embed/BTtbkgO70-E" allowfullscreen="" frameborder="0" height="315" width="420"></iframe>

---

१५ <बी आर >मिनट 
### स्वयं की कहानी बताये

*_स्व संरचना की कहानी के बाद, *_ छोटे समूहों में अपने स्वयं के आख्यान को विकसित करने के लिए शिक्षार्थियों को आमंत्रित करें. अपने स्वयं *\* पर प्रत्येक समूह *\* पहली मंथन करने के लिए कुछ मिनट दे, और फिर उनके छोटे समूह को अपनी कहानी बताने के लिए। *\* कथाकार प्रति 2-3 मिनट दें । **

*\* एक दूसरे को प्रतिक्रिया देने के लिए समूह से पूछो **. कहानियों के बारे में सम्मोहक क्या था? किसी भी महत्वपूर्ण जानकारी या संदर्भ कहाँ गायब है ? कैसे कहानी अगले कह के लिए सुधार किया जा सकता है?

![कार्रवाई में गतिविधि](http://mozilla.github.io/webmaker-curriculum/images/story-of-us-03.jpg)

[ स्टोरी बोर्डिंग  और  स्चेमेटिक्स  क्रैश कोर्स ] के माध्यम से पढ़ें(https://laura.makes.org/thimble/LTEyNzQ2NzQ2ODg=/schematics-and-storyboards), और शिक्षार्थियों उनकी कहानी स्टोरीबोर्ड है ।

---

२ ० <बी आर >मिनट 
### रिकार्ड और प्रतिबिंबित :  हमारी कहानी

**अब रिकॉर्डिंग शुरू करें !** अपने मोबाइल फोन या लैपटॉप पर रिकॉर्डिंग समारोह का उपयोग करना, एक दूसरे की कहानियों रिकॉर्डिंग ले जाता है।

<iframe src="http://plotagon.com/player/42510" webkitallowfullscreen="" mozallowfullscreen="" allowfullscreen="" frameborder="0" height="450" width="100%"></iframe>

**वेब पर विचार करें की क्या अपने शिक्षार्थियों को  उनकी कहानियों को प्रकाशित करने के लिए सेवाओं के लिए सबसे उपयुक्त हैं ?.** साउंडक्लाउड और यूट्यूब आपके  पोस्ट और आसानी से अपनी सामग्री लाइसेंस के लिए अनुमति देते हैं, और ड्रॉपबॉक्स रिकॉर्डिंग भंडारण और आयोजन के लिए एक अच्छा विकल्प भी है. स्टोरीफी आपको वेब से सूत्र एकत्र करने की अनुमति देता है इस [उदाहरण को देखें ](https://storify.com/cpastor24/story-of-us#publiciz). तुम भी शिक्षार्थियों [ वेब पर सेवाओं की एक किस्म का उपयोग ] एनिमेटेड गिफ्ट्स  का उत्पादन कर सकते हो (https://katermouse.makes.org/thimble/LTIwNjQwNTYzMjA=/creative-commons-gif-exchange-activity). वेब पर उनकी कहानियों को प्रकाशित करने के शिक्षार्थियों के लिए कई तरीके हैं । अधिक उदाहरण के लिए, [ इस सूची को देख ](https://github.com/mozilla/teach.webmaker.org/issues/205#issuecomment-84924930) से की वास्तविक उदाहरण [ग्रेग मकवेरर्य  ](http://twitter.com/jgmac1106).

[![](https://d262ilb51hltx0.cloudfront.net/max/760/1*4i87-EgCi3HNvV-_--PjTg.gif)](https://medium.com/@leelefever/welcome-to-the-next-golden-age-of-animated-gifs-56c4851ae33e)

इसके अलावा ऑनलाइन समूह की चर्चा जारी रखने के लिए एक जगह की स्थापना की। [हम वे एक दूसरे के साथ संपर्क में रहने के लिए और साथी शिक्षार्थियों को पूरा कर सकते हैं जहां मोज़िला लर्निंग मंच में शामिल होने की सलाह देते हैं ](http://discourse.webmaker.org/category/clubs).

शिक्षार्थियों अपनी चर्चा मंच के लिए अपनी रिकॉर्डिंग को प्रकाशित किया है. **समझाएं की हर एक व्यक्ति की कहानी भी एक बढ़ी कहानी को धर्षता है : हमारी कहानी , हमारा समूह .**

[![Sanda Htyte](http://mozilla.github.io/webmaker-curriculum/images/story-of-us-02.jpg)](http://www.sandahtyte.com/)

*_एक समूह के रूप में, । अपनी कहानियों पर प्रतिबिंबित *_ प्रक्रिया की तरह क्या था? वे एक दूसरे के बारे में क्या सीखा? कैसे वे दोनों तुल्यकालिक और अतुल्यकालिक चर्चा विकल्पों को ध्यान में रखते हुए , संपर्क में रहने के लिए और एक दूसरे के साथ भाग लेने के लिए चाहते हैं?

वे यहां से जाना चाहते हैं, इस पर एक निर्णय के साथ समाप्त करें ।

२  के बाद गतिविधि प्रश्नावली को पूरा करने से स्थगित : [ अपने शिक्षार्थियों ] के लिए एक(http://goo.gl/forms/8UWO57WswT), और एक [आप] के लिए (http://goo.gl/forms/gUaeABnBuh).

**Comment by soapdog** [comment]
Thanks a lot for the continuous and awesome work! Your contribution is live at:

http://mozilla.github.io/mozilla-club-activity-story-of-us/#hi

Please review it if you can since I had to tweak some of the Markdown syntax and HTML links.

:smile_cat:
