### ISSUE TITLE
Localization of aside.md into Swedish

### ISSUE THREAD

**Issue by bittin** [mozilla/mozilla-club-activity-story-of-us#14]
#### Målgrupp
- 10+
- Begynnande historieberättare
#### Material
- Pennor och papper
- (valfritt) mobiltelefoner, laptop eller annan video/ljud inspelnings utrustning
- (valfritt) [Utskriven berättelse](http://www.scribd.com/doc/198426785/Story-Planning-Worksheet) och [inspelnings tips](http://www.scribd.com/doc/198426782/Recording-and-Interviewing-Basics-Worksheet).
#### Lärandemål
- Använd och dela filer i öppna, webbvänliga format där det går
- Delta i både synkrona och asynkrona diskussioner
- Välj ett webbverktyg som ska användas för ett särskilt bidrag
### Aktiviteten på riktigt!

![Story om OSS i action!](http://mozilla.github.io/webmaker-curriculum/images/story-of-us-01.jpg)
[WNYC Radio Amatörer berättar deras historia](http://hivenyc.org/portfolio/digital-citizenship-kit/).

Se remixar från communityt

Se hur utbildare och aktivister har anpassat aktiviteten för sina specifika målgrupper i vårt [Diskussionsforum](http://discourse.webmaker.org/t/testing-3-participating-on-the-web/1211).

**Comment by soapdog** [comment]
Heeey @bittin, thanks a lot for your contribution. I've added your aside.md to the repo, just waiting for the activity.md.

:smile_cat:

**Comment by bittin** [comment]
will help with the 3 activity.md thats left during next week :)
