### ISSUE TITLE
Localization of activity.md into Swedish

### ISSUE THREAD

**Issue by bittin** [mozilla/mozilla-club-activity-story-of-us#15]
---

title: Story of Us
github: mozilla/mozilla-club-aktivitet-story-of-us
image: phone.png
competencies:
    - {label: "Community Participation", type: "community-participation"}
### Slut Projekt: Story of Us

Skapad av [Mozilla](https://webmaker.org/mentor)för Clubs, baserad på ett projekt av [WNYC Radio Rookies](https://radiorookies.makes.org/thimble/diy-toolkit-how-to-report-your-own-story).

Eleverna kommer att lära sig att berätta sin historia om sig själva, och använda den för att reflektera över vad de har lärt sig, roll lära socialt, och hur de vill lära och delta på webben OCH med samhället framöver. och använda och dela filer i öppna, webbvänliga format när det är lämpligt

1-2 timmar
### Förberedelser

**Gör aktivitet själv** för att bekanta dig med den.

Skriv ut [berättande papper](http://www.scribd.com/doc/198426785/Story-Planning-Worksheet) och [inspelnings tips](http://www.scribd.com/doc/198426782/Recording-och-Interviewing-Basics-Worksheet), om du behöver.

**Genomför den [Den förberedande Enkäten.](http://goo.gl/forms/kAPPY2NDET)**, och be dina studenter att slutföra [deras förberedande enkät](http://goo.gl/forms/KeeMwn7pMJ).

---

10<br>min
### Förstå din Historia om dig själv

Introducera sessionen med att säga att vi kommer att **bygga på vad vi lärt oss än så länge** och använda **webb berättande tekniker** för att dela vår egen resa och reflektera vart vi vill gå härifrån.

> En bra  "Historia om dig själv" har tre delar:
> - **Mig.** Börja din saga med att berätta vem du är. Detta hjälper din publik att förstå dina perspektiv och grunder din historia i din röst och erfarenhet. Fokusera på en aspekt av ditt liv där du stog inför en utmaning och gjorde ett val. Tillexempel, varför du valde att komma till den här gruppen?
> - **Oss.** En effektivt historia broar dina personliga perspektiv med din publik. I denna delen, förklara varför din historia är relevant till din publik. Vilka utmaningar och val som väntar dem? Tillexempel, som en grupp, vilka utmaningar som väntar dig efter idag, och vilka val do you have in response? Kommer ni fortsätta att träffas och lära er saker tillsammans? What will that look like?
> - **Nu.** Du vill att din publik  to leave feeling like they can take action, och that they know what that action is. Present your idea of what the opportunity for now is. Tillexempel, tycker du att gruppen ska fortsätta att träffas varje månad? Eller vill du/ni fortsätta hålla kontakten online? Ge konkreta steg of what can be done next.

Om ni har tid över, kolla på denna korta, animerade video för att höra Amatör Reporter Alexis Gordon förklaragrunderna för rapportering av en bra personlig historia.

<iframe src="https://www.youtube.com/embed/BTtbkgO70-E" allowfullscreen="" frameborder="0" height="315" width="420"></iframe>

---

15<br>min
### Berätta din Story of Self

**Bjud in studenterna att utveckla sina egna berättelser i små grupper**, genom att följa Story of Self strukturen. Ge varje grupp några minuter att **först brainstorma själva**, och sen berätta deras historia till deras mindre grupp. **Tilldela 2-3 minuter per historieberättare.**

Be gruppen att **ge varandra feedback**. Vad var övertygande om berättelser? Var där några viktiga detaljer eller kontext som saknades? Hur skulle historien kunna förbättras för nästa berättande?

![aktivitet i action](http://mozilla.github.io/webmaker-curriculum/images/story-of-us-03.jpg)

Läs igenom [Storyboarding och Schema snabbkursen](https://laura.makes.org/thimble/LTEyNzQ2NzQ2ODg=/schematics-och-storyboards), och be studenterna skissa en storyboard till deras historia.

---

20<br>min
### Spela in och reflektera: The Story of Us

**Nu börja spela in!** Använd inspelningsfunktionen på på din mobiltelefon eller laptop, turas om att spela in varandras historier.

<iframe src="http://plotagon.com/player/42510" webkitallowfullscreen="" mozallowfullscreen="" allowfullscreen="" frameborder="0" height="450" width="100%"></iframe>

**Tänk på vilka Web tjänster som är bäst för dina elever att publicera sina berättelser på.** SoundCloud och YouTube tillåter dig att att ladda upp och licensiera ditt innehåll lätt, och Dropbox är också ett bra alternativ för att lagra och organisera inspelningarna. På Storify kan du samla innehåll från hela webben, bara [se detta exempel](https://storify.com/cpastor24/story-of-us#publiciz). Du kan också be studentera producera animerade gifs [Genom att använda flera olika tjänster på webben](https://katermouse.makes.org/thimble/LTIwNjQwNTYzMjA=/creative-commons-gif-exchange-aktivitet). Det finns många sätt som studenterna kan publicera deras historier på webben t.e.x., [se denna lista](https://github.com/mozilla/teach.webmaker.org/issues/205#issuecomment-84924930) av riktiga exempel från [Greg McVerry](http://twitter.com/jgmac1106).

[![](https://d262ilb51hltx0.cloudfront.net/max/760/1*4i87-EgCi3HNvV-_--PjTg.gif)](https://medium.com/@leelefever/welcome-to-the-next-golden-age-of-animated-gifs-56c4851ae33e)

Ni kan också sätta upp en plats för att fortsätta gruppens diskussioner online. [Vi rekommenderar att gå med i Mozilla Learning forum där de kan hålla kontakten med varandra och träffa andra elever online](http://discourse.webmaker.org/category/clubs).

Be studenterna publisera deras inspelningar på ditt diskussionsforum. **Förklara att varje inviduell historia berättar också en större historia: Historian om oss, av våran grupp.**

[![Socha Htyte](http://mozilla.github.io/webmaker-curriculum/images/story-of-us-02.jpg)](http://www.sochahtyte.com/)

**Som en grupp, reflektera över era berättelser.** Hur såg processen ut? Vad lärde ni er om varandra? Hur skulle de vilja att hålla kontakten och delta med varandra, tänk på både synkrona och asynkrona diskussions alternativ?

Avsluta med ett  beslut om vart **dom vill fortsätta från här**.

Avrunda med att svara på 2 stycken efter-aktivitets enkäter: en för [dina elever](http://goo.gl/forms/8UWO57WswT), och en för [dig](http://goo.gl/forms/gUaeABnBuh).

**Comment by soapdog** [comment]
AWESOME WORK!!!! With this one, we now have a complete curriculum in Swedish! Thanks so much for your hard work! It lives at:

http://mozilla.github.io/mozilla-club-activity-story-of-us/#sv

:smile_cat:
