### ISSUE TITLE
Translation of aside.md into Bengali(bn-BD)

### ISSUE THREAD

**Issue by khalid32** [mozilla/mozilla-club-activity-story-of-us#2]
#### অডিয়েন্স
- ১০+
- শুরুর স্টোরিটেলার
#### উপকরণসমূহ
- কলম এবং কাগজ
- (ঐচ্ছিক) মোবাইল ফোন, ল্যাপটপ অথবা অন্যান্য ভিডিও/অডিও রেকর্ডিং সরঞ্জাম
- (ঐচ্ছিক) [প্রিন্ট করা গল্পগুচ্ছ](http://www.scribd.com/doc/198426785/Story-Planning-Worksheet) এবং [রেকর্ডিং টিপস](http://www.scribd.com/doc/198426782/Recording-and-Interviewing-Basics-Worksheet)।
#### শিক্ষার উদ্দেশ্য
- ফাইলসমূহ মুক্ত, ওয়েব-বান্ধব উপায়ে বিন্যাশ করে ব্যবহার ও শেয়ার করা যখন যথাযত
- উভয় সমকালীন এবং অসমকালীন আলোচনায় অংশগ্রহণ করা
- একটি বিশেষ কন্ট্রিবিউশনে ব্যবহারের জন্য ওয়েব টুল বাছাই করা
### কার্যকলাপের পদক্ষেপ!

![আমাদের গল্প-এর পদক্ষেপ!](http://mozilla.github.io/webmaker-curriculum/images/story-of-us-01.jpg)
[WNYC রেডিও রুকিস তাদের গল্প বলে](http://hivenyc.org/portfolio/digital-citizenship-kit/)।

কমিউনিটির রিমিক্সসমূহ দেখুন

দেখুন শিক্ষাবিদ এবং অ্যাকটিভিস্টরা এই কার্যকলাপ পরিবর্তিত করেছে তাদের সুনির্দিষ্ট অডিয়েন্সের জন্য আমাদের [ডিসকাশন ফরামে](http://discourse.webmaker.org/t/testing-3-participating-on-the-web/1211)।

**Comment by soapdog** [comment]
Heeeey!!!! Thanks a lot for this translation! Its now live at http://mozilla.github.io/mozilla-club-activity-story-of-us/#bn we now have 50% of our activities curriculum already translated into Bengali. Thank you :smile_cat: this is awesome!
