### ISSUE TITLE
Correction localization of aside.md to Bengali (bd)

### ISSUE THREAD

**Issue by mijanurrahman** [mozilla/mozilla-club-activity-story-of-us#3]
#### শ্রোতৃমণ্ডলী
- ১০+
- প্রারম্ভের গল্পকথক
#### উপকরণসমূহ
- কলম এবং কাগজ
- (ঐচ্ছিক) মোবাইল ফোন, ল্যাপটপ অথবা অন্যান্য ভিডিও/অডিও রেকর্ডিং সরঞ্জাম
- (ঐচ্ছিক) [প্রিন্ট করা গল্পগুচ্ছ](http://www.scribd.com/doc/198426785/Story-Planning-Worksheet) এবং [রেকর্ডিং টিপস](http://www.scribd.com/doc/198426782/Recording-and-Interviewing-Basics-Worksheet)।
#### শিক্ষার উদ্দেশ্য
- ফাইলসমূহ মুক্ত, ওয়েব-বান্ধব উপায়ে বিন্যাশ করে ব্যবহার ও শেয়ার করা যখন যথাযত
- উভয় সমকালীন এবং অসমকালীন আলোচনায় অংশগ্রহণ করা
- একটি বিশেষ কন্ট্রিবিউশনে ব্যবহারের জন্য ওয়েব টুল বাছাই করা
### কার্যকলাপের পদক্ষেপ!

![আমাদের গল্প-এর পদক্ষেপ!](http://mozilla.github.io/webmaker-curriculum/images/story-of-us-01.jpg)
[WNYC রেডিও রুকিস তাদের গল্প বলে](http://hivenyc.org/portfolio/digital-citizenship-kit/)।

কমিউনিটির রিমিক্সসমূহ দেখুন

এ দেখুন কিভাবে শিক্ষাবিদ ও কর্মীরা এই কার্যকলাপকে কোন নির্দিষ্ট দর্শকের জন্য রিমিক্স করেছে [আলোচনা ফোরাম](http://discourse.webmaker.org/t/testing-3-participating-on-the-web/1211)।

**Comment by soapdog** [comment]
Thanks a lot for the correction! :+1: Can you describe the changes please? I don't read Bengali... (PS: I've already pushed this live since I believe you fixed only word meanings such as your previous fixes)

Your help has been great, thanks again!
