### ISSUE TITLE
Translation of activity.md into German

### ISSUE THREAD

**Issue by Ryuno-Ki** [mozilla/mozilla-club-activity-story-of-us#5]
---

title: Story of Us
github: mozilla/mozilla-club-activity-story-of-us
image: phone.png
competencies:
    - {label: "Community Participation", type: "community-participation"}
### Finales Projekt: Unsere Geschichte

Produziert von [Mozilla](https://webmaker.org/menter) für Clubs basierend auf einem Projekt von [WNYC Radio Rookies](https://radiorookies.makes.org/thimble/diy-toolkit-how-to-report-your-own-story).

Lernende werden lernen, wie sie Ihre Eigene Geschichte erzählen, wie sie sie zum Reflektieren des Gelernten benutzen, die Rolle des Sozialen Lernens und wie sie künftig lernen und am Web mit ihrer Community teilhaben wollen. Und wie Dateien in einem offenen, web-freundlichen Format genutzt und geteilt werden können, sofern das sinnvoll erscheint.

1-2 Stunden
### Vorbereitung

**Erledige die Aktivität selbst** um damit vertraut zu werden.

Drucke [das Geschichtenerzählen](http://www.scribd.com/doc/198426785/Story-Planning-Worksheet) und [Aufnahme-Tipps](http://www.scribd.com/doc/198426782/Recording-and-Interviewing-Basics-Worksheet) aus, falls du sie brauchst.

**Fülle den [Vorbereitungs-Fragebogen](http://goo.gl/forms/kAPPY2NDET) aus** während die Lernenden [ihren Vorbereitungs-Fragebogen](http://goo.gl/forms/KeeMwn7pMJ) beantworten.

---

10<br>min
### Deine Eigene Geschichte verstehen

Beginne die Stunde damit, dass du sagst, dass wir **auf dem aufbauen, was wir soweit gelernt haben** und **Techniken des Geschichtenerzählens im Web** verwenden werden, um unsere eigene Reise zu teilen und zu reflektieren, wie es von hier aus weitergehen soll.

> Eine gute "Eigene Geschichte" hat drei Teile:
> - **Ich.** Beginne deine Geschichte mit einer Vorstellung von dir. Das hilft deinem Publikum, deine Perspektive zu verstehen und verwurzelt deine Geschichte in deiner Stimme und Erfahrung. Fokussiere einen Aspekt deines Lebens, an dem du vor einer Herausforderung standest und eine Entscheidung fällen musstest. Zum Beispiel, warum hast du dich entschieden, in diese Gruppe zu kommen?
> - **Uns** Eine effektive Geschichte schlägt eine Brücke zwischen deiner persönlichen Ansicht und deinem Publikum. In diesem Abschnitt erkläre, warum deine Geschichte für sie relevant ist. Welche Herausforderungen und Entscheidungen warten auf sie? Zum Beispiel, welchen Hindernissen werden sie als Gruppe nach dem heutigen Tage begegnen und welche Entscheidungsmöglichkeiten haben sie darauf? Werden sie sich weiterhin treffen und gemeinsam lernen? Wie wird das aussehen?
> - **Jetzt.** Du willst, dass dein Publikum mit einem Gefühl aus der Stunde geht, dass sie handeln können und das sie wissen, wie das aussieht. Stelle deine Idee vor, wie die Gelegenheit im Augenblick aussieht. Zum Beispiel, glaubst du, die Gruppe soll sich weiterhin jeden Monat treffen? Wollt ihr online im Kontakt bleiben? Gib konkrete Schritte an, was als nächstes getan werden kann.

Falls es die Zeit zulässt, seht euch diesen Kurzfilm an, indem Rookie Reporter Alexis Gordon erklärt, was die Grundlagen des Erzählens einer guten, eigenen Geschichte ausmacht.

<iframe src="https://www.youtube.com/embed/BTtbkgO70-E" allowfullscreen="" frameborder="0" height="315" width="420"></iframe>

---

15<br>min
### Erzähle deine Eigene Geschichte

**Lade die Lernenden dazu ein, ihr eigene Erzählweise in kleinen Gruppen zu entwickeln**, wobei sie sihc an der Struktur der Eigenen Geschichte halten. Gib jeder Gruppe ein paar Minuten, um **zuerst selber zu brainstormen** und die eigene Geschichte in der Kleingruppe zu erzählen. **Plane 2-3 Minuten pro Geschichtenerzähler ein.**

Bitte die Gruppe, **sich gegenseitig Feedback zu geben**. Was hat an der Geschichte überzeugt? Worin liegen die wichtigen Details und welcher Kontext fehlte? Wie könnte die Geschichte beim nächsten Mal besser erzählt werden?

![Aktivität bei der Arbeit](http://mozilla.github.io/webmaker-curriculum/images/story-of-us-03.jpg)

Lest gemeinsam den [Storyboarding und Schemata Crashkurs](https://laura.makes.org/thimble/LTEyNzQ2NzQ2ODg=/schematics-and-storyboards) und lass die Lernenden ihr eigenes Storyboard zeichnen.

---

20<br>min
### Aufnahme und Reflexion: Unsere Eigene Geschichte

**Beginne jetzt mit der Aufnahme!** Nehmt euch mit der Videoaufnahme eures Smartphones oder Laptops gegenseitig auf und zeigt sie euch anschließend gegenseitig.

<iframe src="http://plotagon.com/player/42510" webkitallowfullscreen="" mozallowfullscreen="" allowfullscreen="" frameborder="0" height="450" width="100%"></iframe>

**Überleg dir, welche Webdienste am ehesten dazu geeignet sind, die Leser ihre eigene Geschichten veröffentlichen zu lassen.** SoundCloud und YouTube erlauben es dir, den Inhalt leicht zu veröffentlichen und zu lizensieren und Dropbox ist auch eine gute Option, die Aufnahmen zu speichern und zu organisieren. Storify erlaubt es dir, Inhalte aus verschiedenen Ecken des Webs zu sammeln, wie [in diesem Beispiel](https://storify.com/cpastor24/story-of-us#publiciz). Du kannst die Lernenden auch animierte GIFs [mithilfe einiger Dienste](https://katermouse.makes.org/thimble/LTIwNjQwNTYzMjA=/creative-commons-gif-exchange-activity) erstellen lassen. Es gibt viele Wege, wie Lernende ihre Geschichten im Web veröffentlichen können. Weitere Beispiele [findest du in dieser Liste](https://github.com/mozilla/teach.webmaker.org/issues/205#issuecomment-84924930) oder reale Beispiele bei [Greg McVerry](http://twitter.com/jgmac1106).

[![](https://d262ilb51hltx0.cloudfront.net/max/760/1*4i87-EgCi3HNvV-_--PjTg.gif)](https://medium.com/@leelefever/welcome-to-the-next-golden-age-of-animated-gifs-56c4851ae33e)

Bereite auch einen Platz vor, um die Gruppen-Diskussion online fortzuführen. [Wir empfehlen dem Beitreten des Mozilla Learning Forums, wo sie miteinander im Kontakt bleiben und andere Lernende treffen können](http://discourse.webmaker.org/category/clubs).

Lass die Lernenden ihre Aufnahmen im Diskussions-Forum hochladen. **Erkläre, dass jede einzelne Geschichte auch eine größere Geschichte erzählt: Unsere Geschichte, die Geschichte unserer Gruppe.**

[![Sanda Htyte](http://mozilla.github.io/webmaker-curriculum/images/story-of-us-02.jpg)](http://www.sandahtyte.com/)

**Reflektiert eure Geschichten als Gruppe.** Wie empfandet ihr den Prozess? Was habt ihr von einander gelernt? Wie wollt ihr in Kontakt bleiben und aneinander teilhaben? Bedenkt, dass es sowohl synchrone als auch asynchrone Diskussionsmöglichkeiten gibt.

Schließe die Entscheidung damit, **wie es von hier an weitergehen soll**.

Teile dann zwei Nachbereitungs-Fragebögen aus: einen für [die Lernenden](http://goo.gl/forms/8UWO57WswT) und einen für [dich](http://goo.gl/forms/gUaeABnBuh).

**Comment by Ryuno-Ki** [comment]
I'd welcome a second reviewer on this. On some occassions (like with "reflect" or "record") I was not finally sure, which word to pick - it depends on how much German the reader understand.

Also, I'm not sure, whether English videos and forums etc. are the best choice to link, too.

**Comment by soapdog** [comment]
:smiley_cat: thanks a lot for your continuous support of this initiative :smile_cat: 

I've merged your translation and it is now available! Yay!!!!

As for the English videos and forums, I believe the forum interface is localized in German if that is your browser language and we could create areas for specific locales there. As for the videos, maybe we can find a way to add soft subtitles. Would that be good?
