### ISSUE TITLE
Translation of aside.md into German

### ISSUE THREAD

**Issue by Ryuno-Ki** [mozilla/mozilla-club-activity-story-of-us#6]
#### Publikum
- 10+
- Geschichtenerzähler-Beginner
#### Material
- Stift und Papier
- (optional) Smartphones, Laptop oder andere Video-/Audio-Aufnahme-Ausrüstung
- (optional) [Ausgedrucktes Storytelling](http://www.scribd.com/doc/198426785/Story-Planning-Worksheet) und [Aufnahme-Tipps](http://www.scribd.com/doc/198426782/Recording-and-Interviewing-Basics-Worksheet).
#### Lernziele
- Nutzen und Teilen von Dateien in offenen, web-freundlichen Formaten sofern angemessen
- Teilhabe in sowohl synchronen als auch asynchronen Diskussionen
- Wahl eines Web-Werkzeuges für einen bestimmten Beitrag
#### Aktivität bei der Arbeit

![US-Story in Aktion!](http://mozilla.github.io/webmaker-curriculum/images/story-of-us-01.jpg)
[WNYC Radio Rookies erzählen ihre Geschichte](http://hivenyc.org/portfolio/digital-citizenship-kit/).

Weitere Community-Remixes

Siehe auch weitere Wege in unserem [Diskussions-Forum](http://discourse.webmaker.org/t/testing-3-participating-on-the-web/1211), wie Lehrende und Aktivisten diese Aktivität für ihr Publikum abgewandelt haben.

**Comment by soapdog** [comment]
:smiley_cat: thanks a lot for your continuous support of this initiative :smile_cat: 

I've merged your translation and it is now available! Yay!!!!
