### ISSUE TITLE
Missing h4 for further remixes

### ISSUE THREAD

**Issue by Ryuno-Ki** [mozilla/mozilla-club-activity-story-of-us#7]
In [Kraken the Code](https://github.com/mozilla/mozilla-club-activity-story-of-us/blob/edb664873899e9b7a6d9d0bc4036b977d68b0a14/activity-data/content/en/aside.md) the "see content remixes" is written as plain line, whereas it is an `h4` in [Story of Us](https://github.com/mozilla/mozilla-club-activity-kraken-the-code/blob/010b087f5760ff3961530ebe7c44aeea054b454b/activity-data/content/en/aside.md)

I assume, the latter is wrong. Please notify submitters/correct existing submissions as well.

**Comment by soapdog** [comment]
Changed the ones in this activity to `h4` because it draws attention to the remixes which I think it is a good thing, also, it looks good.

I've changed all the locales.
